cmake_minimum_required(VERSION 4.4)

set(repo_root "${CMAKE_CURRENT_LIST_DIR}/..")
cmake_path(NORMAL_PATH repo_root)

function(resolve_input output variable default_path)
  if(DEFINED ${variable})
    set(path "${${variable}}")
  else()
    set(path "${repo_root}/${default_path}")
  endif()
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "Missing C++ release contract input: ${path}")
  endif()
  set(${output} "${path}" PARENT_SCOPE)
endfunction()

function(read_json_object output path label)
  file(READ "${path}" contents)
  string(JSON root_type ERROR_VARIABLE json_error TYPE "${contents}")
  if(json_error OR NOT root_type STREQUAL "OBJECT")
    message(FATAL_ERROR "${label} must be a JSON object: ${json_error}")
  endif()
  string(JSON schema_version ERROR_VARIABLE version_error GET "${contents}" schemaVersion)
  if(version_error OR NOT schema_version EQUAL 1)
    message(FATAL_ERROR "${label} must have schemaVersion 1")
  endif()
  set(${output} "${contents}" PARENT_SCOPE)
endfunction()

function(require_nonempty_string json path label)
  string(JSON value_type ERROR_VARIABLE type_error TYPE "${json}" ${path})
  string(JSON value ERROR_VARIABLE value_error GET "${json}" ${path})
  string(STRIP "${value}" stripped_value)
  if(type_error OR NOT value_type STREQUAL "STRING" OR value_error OR stripped_value STREQUAL "")
    message(FATAL_ERROR "${label} must be a non-empty string")
  endif()
endfunction()

function(require_structured_payload json identity_key label)
  string(JSON member_count ERROR_VARIABLE count_error LENGTH "${json}")
  if(count_error OR member_count LESS 3)
    message(FATAL_ERROR
      "${label} must contain release data beyond schemaVersion and ${identity_key}")
  endif()

  math(EXPR last_member "${member_count} - 1")
  set(has_payload FALSE)
  foreach(index RANGE 0 ${last_member})
    string(JSON member_name ERROR_VARIABLE member_error MEMBER "${json}" ${index})
    if(member_error)
      message(FATAL_ERROR "${label} has an unreadable top-level member")
    endif()
    if(NOT member_name STREQUAL "schemaVersion" AND NOT member_name STREQUAL "${identity_key}")
      string(JSON member_type ERROR_VARIABLE type_error TYPE "${json}" "${member_name}")
      if(type_error)
        message(FATAL_ERROR "${label} has an unreadable ${member_name} member")
      endif()
      if(member_type STREQUAL "OBJECT" OR member_type STREQUAL "ARRAY")
        string(JSON payload_length ERROR_VARIABLE payload_error LENGTH "${json}" "${member_name}")
        if(payload_error)
          message(FATAL_ERROR "${label} has an unreadable ${member_name} payload")
        endif()
        if(payload_length GREATER 0)
          set(has_payload TRUE)
        endif()
      endif()
    endif()
  endforeach()

  if(NOT has_payload)
    message(FATAL_ERROR "${label} must contain a non-empty object or array payload")
  endif()
endfunction()

function(json_contains_linux_x86_64 json path output)
  set(found FALSE)
  string(JSON node_type ERROR_VARIABLE node_error TYPE "${json}" ${path})
  if(NOT node_error)
    if(node_type STREQUAL "OBJECT")
      string(JSON platform_type ERROR_VARIABLE platform_type_error TYPE "${json}" ${path} platform)
      string(JSON architecture_type ERROR_VARIABLE architecture_type_error TYPE "${json}" ${path} architecture)
      if(NOT platform_type_error AND NOT architecture_type_error
          AND platform_type STREQUAL "STRING" AND architecture_type STREQUAL "STRING")
        string(JSON platform ERROR_VARIABLE platform_error GET "${json}" ${path} platform)
        string(JSON architecture ERROR_VARIABLE architecture_error GET "${json}" ${path} architecture)
        if(NOT platform_error AND NOT architecture_error
            AND platform STREQUAL "linux" AND architecture STREQUAL "x86_64")
          set(found TRUE)
        endif()
      endif()

      if(NOT found)
        string(JSON member_count ERROR_VARIABLE count_error LENGTH "${json}" ${path})
        if(NOT count_error)
          math(EXPR last_member "${member_count} - 1")
          if(last_member GREATER_EQUAL 0)
            foreach(index RANGE 0 ${last_member})
              string(JSON member_name ERROR_VARIABLE member_error MEMBER "${json}" ${path} ${index})
              if(NOT member_error)
                if(path STREQUAL "")
                  set(child_path "${member_name}")
                else()
                  set(child_path "${path};${member_name}")
                endif()
                json_contains_linux_x86_64("${json}" "${child_path}" child_found)
                if(child_found)
                  set(found TRUE)
                  break()
                endif()
              endif()
            endforeach()
          endif()
        endif()
      endif()
    elseif(node_type STREQUAL "ARRAY")
      string(JSON item_count ERROR_VARIABLE count_error LENGTH "${json}" ${path})
      if(NOT count_error)
        math(EXPR last_item "${item_count} - 1")
        if(last_item GREATER_EQUAL 0)
          foreach(index RANGE 0 ${last_item})
            if(path STREQUAL "")
              set(child_path "${index}")
            else()
              set(child_path "${path};${index}")
            endif()
            json_contains_linux_x86_64("${json}" "${child_path}" child_found)
            if(child_found)
              set(found TRUE)
              break()
            endif()
          endforeach()
        endif()
      endif()
    endif()
  endif()
  set(${output} "${found}" PARENT_SCOPE)
endfunction()

function(require_linux_x86_64_profile path)
  file(READ "${path}" contents)
  json_contains_linux_x86_64("${contents}" "" has_linux_x86_64)
  if(NOT has_linux_x86_64)
    message(FATAL_ERROR "reference profiles must include a Linux x86_64 record")
  endif()
endfunction()

resolve_input(runtime_lock RUNTIME_LOCK packaging/runtime-lock.json)
resolve_input(reference_profiles REFERENCE_PROFILES packaging/reference-profiles-v1.json)
resolve_input(evidence_schema EVIDENCE_SCHEMA packaging/evidence-schema-v1.json)
resolve_input(release_evidence_schema RELEASE_EVIDENCE_SCHEMA packaging/release-evidence-schema-v1.json)

read_json_object(runtime_lock_json "${runtime_lock}" "runtime lock")
read_json_object(reference_profiles_json "${reference_profiles}" "reference profiles")
require_nonempty_string("${runtime_lock_json}" lockId "runtime lock lockId")
require_structured_payload("${runtime_lock_json}" lockId "runtime lock")
require_nonempty_string("${reference_profiles_json}" profileSetId "reference profiles profileSetId")
require_structured_payload("${reference_profiles_json}" profileSetId "reference profiles")
require_linux_x86_64_profile("${reference_profiles}")

set(schema_paths "${evidence_schema}" "${release_evidence_schema}")
set(schema_labels "evidence schema" "release evidence schema")
foreach(schema_path schema_label IN ZIP_LISTS schema_paths schema_labels)
  file(READ "${schema_path}" schema_json)
  string(JSON root_type ERROR_VARIABLE schema_error TYPE "${schema_json}")
  if(schema_error OR NOT root_type STREQUAL "OBJECT")
    message(FATAL_ERROR "${schema_label} must be a JSON object: ${schema_error}")
  endif()
  string(JSON dialect ERROR_VARIABLE dialect_error GET "${schema_json}" "$schema")
  string(JSON schema_version ERROR_VARIABLE version_error GET "${schema_json}" properties schemaVersion const)
  if(dialect_error OR NOT dialect STREQUAL "https://json-schema.org/draft/2020-12/schema")
    message(FATAL_ERROR "${schema_label} must use JSON Schema Draft 2020-12")
  endif()
  if(version_error OR NOT schema_version EQUAL 1)
    message(FATAL_ERROR "${schema_label} must fix schemaVersion to 1")
  endif()
endforeach()

message(STATUS "C++ release contract OK")
