cmake_minimum_required(VERSION 4.4)

set(repo_root "${CMAKE_CURRENT_LIST_DIR}/..")
cmake_path(NORMAL_PATH repo_root)

function(resolve_input output variable default_path)
  if(DEFINED ${variable})
    set(path "${${variable}}")
  else()
    set(path "${repo_root}/${default_path}")
  endif()
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "Missing C++ release contract input: ${path}")
  endif()
  set(${output} "${path}" PARENT_SCOPE)
endfunction()

function(read_json_object output path label)
  file(READ "${path}" contents)
  string(JSON root_type ERROR_VARIABLE json_error TYPE "${contents}")
  if(json_error OR NOT root_type STREQUAL "OBJECT")
    message(FATAL_ERROR "${label} must be a JSON object: ${json_error}")
  endif()
  string(JSON schema_version ERROR_VARIABLE version_error GET "${contents}" schemaVersion)
  if(version_error OR NOT schema_version EQUAL 1)
    message(FATAL_ERROR "${label} must have schemaVersion 1")
  endif()
  set(${output} "${contents}" PARENT_SCOPE)
endfunction()

resolve_input(runtime_lock RUNTIME_LOCK packaging/runtime-lock.json)
resolve_input(reference_profiles REFERENCE_PROFILES packaging/reference-profiles-v1.json)
resolve_input(evidence_schema EVIDENCE_SCHEMA packaging/evidence-schema-v1.json)
resolve_input(release_evidence_schema RELEASE_EVIDENCE_SCHEMA packaging/release-evidence-schema-v1.json)

read_json_object(runtime_lock_json "${runtime_lock}" "runtime lock")
read_json_object(reference_profiles_json "${reference_profiles}" "reference profiles")

set(schema_paths "${evidence_schema}" "${release_evidence_schema}")
set(schema_labels "evidence schema" "release evidence schema")
foreach(schema_path schema_label IN ZIP_LISTS schema_paths schema_labels)
  file(READ "${schema_path}" schema_json)
  string(JSON root_type ERROR_VARIABLE schema_error TYPE "${schema_json}")
  if(schema_error OR NOT root_type STREQUAL "OBJECT")
    message(FATAL_ERROR "${schema_label} must be a JSON object: ${schema_error}")
  endif()
  string(JSON dialect ERROR_VARIABLE dialect_error GET "${schema_json}" "$schema")
  string(JSON schema_version ERROR_VARIABLE version_error GET "${schema_json}" properties schemaVersion const)
  if(dialect_error OR NOT dialect STREQUAL "https://json-schema.org/draft/2020-12/schema")
    message(FATAL_ERROR "${schema_label} must use JSON Schema Draft 2020-12")
  endif()
  if(version_error OR NOT schema_version EQUAL 1)
    message(FATAL_ERROR "${schema_label} must fix schemaVersion to 1")
  endif()
endforeach()

message(STATUS "C++ release contract OK")
