cmake_minimum_required(VERSION 4.4)

if(DEFINED TRACEABILITY_PLAN)
  set(plan "${TRACEABILITY_PLAN}")
else()
  set(plan "${CMAKE_CURRENT_LIST_DIR}/../docs/specs/cpp23-implementation-plan.md")
endif()
if(DEFINED TRACEABILITY_SPEC)
  set(spec "${TRACEABILITY_SPEC}")
else()
  set(spec "${CMAKE_CURRENT_LIST_DIR}/../docs/specs/fully-native-melearner.md")
endif()
foreach(required IN ITEMS "${plan}" "${spec}")
  if(NOT EXISTS "${required}")
    message(FATAL_ERROR "Missing C++ planning source: ${required}")
  endif()
endforeach()

file(STRINGS "${plan}" plan_table_rows REGEX "^\\|")
list(LENGTH plan_table_rows plan_table_count)
if(NOT plan_table_count EQUAL 78)
  message(FATAL_ERROR "Expected exactly two planning tables with 78 rows, found ${plan_table_count}")
endif()

file(STRINGS "${plan}" ticket_rows REGEX "^\\| T[0-9]")
list(LENGTH ticket_rows ticket_count)
if(NOT ticket_count EQUAL 34)
  message(FATAL_ERROR "Expected 34 ticket rows, found ${ticket_count}")
endif()

set(ticket_keys)
set(ticket_issues)
foreach(line IN LISTS ticket_rows)
  if(NOT line MATCHES "^\\| T([0-9][0-9]) \\| #([0-9]+) \\| ([^|]+) \\| ([^|]+) \\|$")
    message(FATAL_ERROR "Malformed ticket row: ${line}")
  endif()

  set(key "${CMAKE_MATCH_1}")
  set(issue "${CMAKE_MATCH_2}")
  string(STRIP "${CMAKE_MATCH_3}" title)
  string(STRIP "${CMAKE_MATCH_4}" blockers)
  if(title STREQUAL "")
    message(FATAL_ERROR "T${key} has an empty title")
  endif()

  list(FIND ticket_keys "${key}" duplicate_key)
  list(FIND ticket_issues "${issue}" duplicate_issue)
  if(NOT duplicate_key EQUAL -1 OR NOT duplicate_issue EQUAL -1)
    message(FATAL_ERROR "Duplicate ticket key or issue in row: ${line}")
  endif()

  string(REGEX REPLACE "^0" "" key_number "${key}")
  math(EXPR expected_issue "31 + ${key_number}")
  if(NOT issue EQUAL expected_issue)
    message(FATAL_ERROR "T${key} must map to #${expected_issue}, found #${issue}")
  endif()

  if(key STREQUAL "01")
    if(NOT blockers STREQUAL "None")
      message(FATAL_ERROR "T01 must be the only root ticket")
    endif()
  else()
    if(blockers STREQUAL "None")
      message(FATAL_ERROR "T${key} must be reachable from an earlier ticket")
    endif()
    string(REPLACE ", " ";" blocker_list "${blockers}")
    set(seen_blockers)
    foreach(blocker IN LISTS blocker_list)
      if(NOT blocker MATCHES "^T[0-9][0-9]$")
        message(FATAL_ERROR "Malformed blocker ${blocker} in T${key}")
      endif()
      list(FIND seen_blockers "${blocker}" duplicate_blocker)
      if(NOT duplicate_blocker EQUAL -1)
        message(FATAL_ERROR "T${key} repeats blocker ${blocker}")
      endif()
      list(APPEND seen_blockers "${blocker}")
      string(SUBSTRING "${blocker}" 1 2 blocker_key)
      list(FIND ticket_keys "${blocker_key}" blocker_index)
      if(blocker_index EQUAL -1)
        message(FATAL_ERROR "T${key} has an unknown, forward, or cyclic blocker: ${blocker}")
      endif()
    endforeach()
  endif()

  list(APPEND ticket_keys "${key}")
  list(APPEND ticket_issues "${issue}")
endforeach()

foreach(expected RANGE 1 34)
  if(expected LESS 10)
    set(key "0${expected}")
  else()
    set(key "${expected}")
  endif()
  list(FIND ticket_keys "${key}" key_index)
  if(key_index EQUAL -1)
    message(FATAL_ERROR "Missing T${key}")
  endif()
endforeach()

file(STRINGS "${spec}" canonical_story_rows REGEX "^[0-9]+\\. \\*\\*")
list(LENGTH canonical_story_rows canonical_story_count)
if(NOT canonical_story_count EQUAL 40)
  message(FATAL_ERROR "Expected 40 canonical stories, found ${canonical_story_count}")
endif()

set(canonical_story_keys)
foreach(line IN LISTS canonical_story_rows)
  if(NOT line MATCHES "^([0-9]+)\\. \\*\\*S([0-9]+)\\.\\*\\* .+$")
    message(FATAL_ERROR "Malformed canonical story: ${line}")
  endif()
  if(NOT CMAKE_MATCH_1 EQUAL CMAKE_MATCH_2)
    message(FATAL_ERROR "Story ordinal and ID differ: ${line}")
  endif()
  list(APPEND canonical_story_keys "${CMAKE_MATCH_2}")
endforeach()

file(STRINGS "${plan}" story_rows REGEX "^\\| S[0-9]")
list(LENGTH story_rows story_count)
if(NOT story_count EQUAL 40)
  message(FATAL_ERROR "Expected 40 primary story rows, found ${story_count}")
endif()

set(story_keys)
foreach(line IN LISTS story_rows)
  if(NOT line MATCHES "^\\| S([0-9]+) \\| T([0-9][0-9]) \\| #([0-9]+) \\|$")
    message(FATAL_ERROR "Malformed story ownership row: ${line}")
  endif()

  set(story "${CMAKE_MATCH_1}")
  set(ticket "${CMAKE_MATCH_2}")
  set(issue "${CMAKE_MATCH_3}")
  list(FIND story_keys "${story}" duplicate_story)
  list(FIND canonical_story_keys "${story}" canonical_index)
  list(FIND ticket_keys "${ticket}" ticket_index)
  if(NOT duplicate_story EQUAL -1)
    message(FATAL_ERROR "S${story} has more than one primary owner")
  endif()
  if(canonical_index EQUAL -1)
    message(FATAL_ERROR "Ownership row refers to unknown S${story}")
  endif()
  if(ticket_index EQUAL -1)
    message(FATAL_ERROR "Ownership row refers to unknown T${ticket}")
  endif()
  list(GET ticket_issues "${ticket_index}" ticket_issue)
  if(NOT issue EQUAL ticket_issue)
    message(FATAL_ERROR "S${story} maps T${ticket} to #${issue}, expected #${ticket_issue}")
  endif()
  list(APPEND story_keys "${story}")
endforeach()

foreach(expected RANGE 1 40)
  list(FIND story_keys "${expected}" story_index)
  if(story_index EQUAL -1)
    message(FATAL_ERROR "S${expected} has no primary owner")
  endif()
endforeach()

message(STATUS "C++ traceability OK: 34 acyclic tickets, 40 canonical stories, one primary owner each")
